//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFoodCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFoodCategory()
        {
            this.tblFoodProducts = new HashSet<tblFoodProduct>();
        }
    
        public int FOOD_CATEGORY_ID { get; set; }
        public string FOOD_CATEGORY_NAME { get; set; }
        public string FOOD_CATEGORY_PICTURE { get; set; }
        public string PicLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFoodProduct> tblFoodProducts { get; set; }
    }
}
