//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfeedback
    {
        public int FEEDBACK_ID { get; set; }
        public string FEEDBACK_DESCRIPTION { get; set; }
        public string FEEDBACK_NAME { get; set; }
        public int WHATSAPP_NO { get; set; }
        public int PHONE_NO { get; set; }
        public string ADDRESS { get; set; }
    }
}
