//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFoodProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFoodProduct()
        {
            this.tblIngredientLinkings = new HashSet<tblIngredientLinking>();
            this.tblOrderDetails = new HashSet<tblOrderDetail>();
        }
    
        public int FOOD_PRODUCTS_ID { get; set; }
        public string FOOD_PRODUCTS_NAME { get; set; }
        public decimal FOOD_PRODUCTS_PRICE { get; set; }
        public string FOOD_PRODUCTS_PICTURE { get; set; }
        public int FOOD_CATEGORY_FID { get; set; }
        public string PicLink { get; set; }
    
        public virtual tblFoodCategory tblFoodCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIngredientLinking> tblIngredientLinkings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
    }
}
