//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIngredientLinking
    {
        public int INGREDIENT_LINKING_ID { get; set; }
        public int FOOD_PRODUCTS_FID { get; set; }
        public int INGREDIENT_FID { get; set; }
        public decimal INGREDIENT_LINKING_QUANTITY { get; set; }
    
        public virtual tblFoodProduct tblFoodProduct { get; set; }
        public virtual tblIngredient tblIngredient { get; set; }
    }
}
