//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIngredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblIngredient()
        {
            this.tblIngredientLinkings = new HashSet<tblIngredientLinking>();
            this.tblOrderLinkings = new HashSet<tblOrderLinking>();
            this.tblOrderPurchaseDetails = new HashSet<tblOrderPurchaseDetail>();
        }
    
        public int INGREDIENT_ID { get; set; }
        public string INGREDIENT_NAME { get; set; }
        public decimal INGREDIENT_PRICE { get; set; }
        public decimal INGREDIENT_UNIT_PRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIngredientLinking> tblIngredientLinkings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderLinking> tblOrderLinkings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderPurchaseDetail> tblOrderPurchaseDetails { get; set; }
    }
}
