//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderPurchase
    {
        public int ORDER_PURCHASE_ID { get; set; }
        public System.DateTime ORDER_PURCHASE_DATE_TIME { get; set; }
        public int WORKER_FID { get; set; }
    
        public virtual tblWorker tblWorker { get; set; }
    }
}
