//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderLinking
    {
        public int ORDER_LINKING_ID { get; set; }
        public int INGREDIENT_FID { get; set; }
        public int ORDER_DETAILS_FID { get; set; }
        public decimal ORDER_LINKING_PRICE { get; set; }
    
        public virtual tblIngredient tblIngredient { get; set; }
        public virtual tblOrderDetail tblOrderDetail { get; set; }
    }
}
