//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblOrderDetails = new HashSet<tblOrderDetail>();
            this.tblRiderAssigningOrders = new HashSet<tblRiderAssigningOrder>();
        }
    
        public int ORDER_ID { get; set; }
        public string ORDER_CUSTOMER_NAME { get; set; }
        public string ORDER_CUSTOMER_ADDRESS { get; set; }
        public string ORDER_CUSTOMER_CONTACT { get; set; }
        public string ORDER_STATUS { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public string ORDER_PAYMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRiderAssigningOrder> tblRiderAssigningOrders { get; set; }
    }
}
