//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrderDetail()
        {
            this.tblOrderLinkings = new HashSet<tblOrderLinking>();
        }
    
        public int ORDER_DETAILS_ID { get; set; }
        public int ORDER_FID { get; set; }
        public int FOOD_PRODUCTS_FID { get; set; }
        public decimal ORDER_DETAILS_QUANTITY { get; set; }
        public decimal ORDER_DETAILS_PRICE { get; set; }
        public Nullable<bool> ORDER_DETAILS_isAdding { get; set; }
        public Nullable<bool> Ispicking { get; set; }
    
        public virtual tblFoodProduct tblFoodProduct { get; set; }
        public virtual tblOrder tblOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderLinking> tblOrderLinkings { get; set; }
    }
}
