//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRider()
        {
            this.tblRiderAssigningOrders = new HashSet<tblRiderAssigningOrder>();
            this.tblWorkerDetails = new HashSet<tblWorkerDetail>();
        }
    
        public int RIDER_ID { get; set; }
        public string RIDER_NAME { get; set; }
        public string RIDER_CONTACT { get; set; }
        public string RIDER_ADDRESS { get; set; }
        public decimal RIDER_PAY { get; set; }
        public string LocationRider { get; set; }
        public string RIDER_EMAIL { get; set; }
        public string RIDER_PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRiderAssigningOrder> tblRiderAssigningOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkerDetail> tblWorkerDetails { get; set; }
    }
}
