//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRiderAssigningOrder
    {
        public int RIDER_ASSIGNING_ORDER_ID { get; set; }
        public int ORDER_FID { get; set; }
        public int RIDER_FID { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
        public virtual tblRider tblRider { get; set; }
    }
}
