//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWorker()
        {
            this.tblOrderPurchases = new HashSet<tblOrderPurchase>();
        }
    
        public int WORKER_ID { get; set; }
        public string WORKER_NAME { get; set; }
        public string WORKER_EMAIL { get; set; }
        public string WORKER_PASSWORD { get; set; }
        public string WORKER_CONTACT { get; set; }
        public string WORKER_ADDRESS { get; set; }
        public string WORKER_PICTURES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderPurchase> tblOrderPurchases { get; set; }
    }
}
