//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkerDetail
    {
        public int WORKER_DETAIL_ID { get; set; }
        public int WORKER_FID { get; set; }
        public System.DateTime WORKER_IN_TIME { get; set; }
        public System.DateTime WORKER_OUT_TIME { get; set; }
        public string WORKER_LEAVE_REASON { get; set; }
        public int RIDER_FID { get; set; }
    
        public virtual tblRider tblRider { get; set; }
    }
}
